# Generated by Django 4.0.1 on 2022-01-29 14:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_active_project_featured_project_sub_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_headline',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
