# Generated by Django 4.0.1 on 2022-01-29 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_project_sub_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_headline',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
