# Generated by Django 4.0.1 on 2022-02-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_headline',
            field=models.CharField(blank=True, default='/images/default.jpg', max_length=200, null=True),
        ),
    ]
