# Generated by Django 4.0.1 on 2022-02-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_project_sub_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/default.jpg', null=True, upload_to='images'),
        ),
    ]
