# Generated by Django 4.0.1 on 2022-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_project_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
