# Generated by Django 4.0.1 on 2022-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='images/placeholder.png', null=True, upload_to='images'),
        ),
    ]
