# Generated by Django 4.0.1 on 2022-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='sub_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
