# Generated by Django 4.0.1 on 2022-02-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_skill_sub_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
