# Generated by Django 4.0.1 on 2022-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SourceLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
