# Generated by Django 4.0.1 on 2022-02-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_project_sourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='APILink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
