# Generated by Django 4.0.1 on 2022-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_qualification_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='bx bx-code', max_length=200, null=True),
        ),
    ]
