# Generated by Django 4.0.1 on 2022-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_about_home_delete_endorsement_delete_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
