# Generated by Django 4.0.1 on 2022-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_about_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
